/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "serial.h"
#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define MSG_TYPE_TEXT    0x01
#define MSG_TYPE_SENSOR  0x02

typedef struct {
    uint16_t heading;
    uint8_t  button_state;
} SensorData;



static void on_message_received_part_f(uint8_t *data, uint8_t size, uint8_t type)
{
    if (type == MSG_TYPE_TEXT) {
        sendStringIT((uint8_t *)"MSG TYPE: TEXT\r\n", &USART1_PORT);
    } else if (type == MSG_TYPE_SENSOR) {
        sendStringIT((uint8_t *)"MSG TYPE: SENSOR\r\n", &USART1_PORT);
    } else {
        sendStringIT((uint8_t *)"MSG TYPE: UNKNOWN\r\n", &USART1_PORT);
    }

    while (SerialTxBusy()) {}
    sendMsgIT(data, size, type, &USART1_PORT);
}




static void on_message_received(uint8_t *data, uint8_t size, uint8_t type)
{
    if (type == MSG_TYPE_TEXT) {
        sendString((uint8_t *)"MSG TYPE: TEXT\r\n", &USART1_PORT);
    } else if (type == MSG_TYPE_SENSOR) {
        sendString((uint8_t *)"MSG TYPE: SENSOR\r\n", &USART1_PORT);
    } else {
        sendString((uint8_t *)"MSG TYPE: UNKNOWN\r\n", &USART1_PORT);
    }
    sendMsg(data, size, type, &USART1_PORT);
}

int main(void)
{
    SerialInitialise(BAUD_115200, &USART1_PORT, 0);

    uint8_t part = 'e';

    switch (part)
    {
        case 'a': {
            uint8_t *string_to_send = (uint8_t *)"abcd";
            SerialOutputString(string_to_send, &USART1_PORT);

            uint8_t string_to_receive[5] = {0};
            SerialReceiveString(string_to_receive, 5, &USART1_PORT);

            while (1) {}
        }

        case 'b': {
            uint8_t *debug_string = (uint8_t *)"Debug: Part B sendString working\r\n";
            sendString(debug_string, &USART1_PORT);

            while (1) {}
        }

        case 'c': {
            uint8_t text_body[] = "HI";
            sendMsg(text_body, sizeof(text_body) - 1, MSG_TYPE_TEXT, &USART1_PORT);

            for (volatile uint32_t i = 0; i < 500000; i++) {}

            SensorData sensor;
            sensor.heading = 275;
            sensor.button_state = 1;
            sendMsg(&sensor, sizeof(sensor), MSG_TYPE_SENSOR, &USART1_PORT);

            while (1) {}
        }

        case 'd': {
            sendString((uint8_t *)"Part D: waiting for message...\r\n", &USART1_PORT);

            while (1) {
                receiveMsgPolling(&USART1_PORT, &on_message_received);
            }
        }

        case 'e': {
            enable_interrupt(&USART1_PORT);  // only enable here
            sendString((uint8_t *)"Part E: interrupt receive ready\r\n", &USART1_PORT);

            while (1) {
                receiveMsg(&USART1_PORT, &on_message_received);
            }
        }
        case 'f': {
                    enable_interrupt_part_f(&USART1_PORT);

                    sendStringIT((uint8_t *)"Part F: TX interrupt + RX double buffer ready\r\n", &USART1_PORT);

                    while (1) {
                        receiveMsgDoubleBuffer(&USART1_PORT, &on_message_received_part_f);
                    }
        }

    }
}
